--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.CLIENT_SERVER_REQ = protobuf.Descriptor();
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD = protobuf.FieldDescriptor();
_M.CLIENT_SERVER_RES = protobuf.Descriptor();
_M.CLIENT_SERVER_RES_IERROR_FIELD = protobuf.FieldDescriptor();
_M.CLIENT_SERVER_RES_ISERVERID_FIELD = protobuf.FieldDescriptor();
_M.CLIENT_SERVER_RES_SZIP_FIELD = protobuf.FieldDescriptor();
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD = protobuf.FieldDescriptor();
_M.CLIENT_SERVER_RES_WPORT_FIELD = protobuf.FieldDescriptor();

_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.name = "iServerId"
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.full_name = ".lobby_gateway.client_server_req.iServerId"
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.number = 1
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.index = 0
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.label = 1
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.has_default_value = true
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.default_value = 0
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.type = 13
_M.CLIENT_SERVER_REQ_ISERVERID_FIELD.cpp_type = 3

_M.CLIENT_SERVER_REQ.name = "client_server_req"
_M.CLIENT_SERVER_REQ.full_name = ".lobby_gateway.client_server_req"
_M.CLIENT_SERVER_REQ.nested_types = {}
_M.CLIENT_SERVER_REQ.enum_types = {}
_M.CLIENT_SERVER_REQ.fields = {_M.CLIENT_SERVER_REQ_ISERVERID_FIELD}
_M.CLIENT_SERVER_REQ.is_extendable = false
_M.CLIENT_SERVER_REQ.extensions = {}
_M.CLIENT_SERVER_RES_IERROR_FIELD.name = "iError"
_M.CLIENT_SERVER_RES_IERROR_FIELD.full_name = ".lobby_gateway.client_server_res.iError"
_M.CLIENT_SERVER_RES_IERROR_FIELD.number = 1
_M.CLIENT_SERVER_RES_IERROR_FIELD.index = 0
_M.CLIENT_SERVER_RES_IERROR_FIELD.label = 1
_M.CLIENT_SERVER_RES_IERROR_FIELD.has_default_value = true
_M.CLIENT_SERVER_RES_IERROR_FIELD.default_value = 0
_M.CLIENT_SERVER_RES_IERROR_FIELD.type = 13
_M.CLIENT_SERVER_RES_IERROR_FIELD.cpp_type = 3

_M.CLIENT_SERVER_RES_ISERVERID_FIELD.name = "iServerId"
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.full_name = ".lobby_gateway.client_server_res.iServerId"
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.number = 2
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.index = 1
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.label = 1
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.has_default_value = true
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.default_value = 0
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.type = 13
_M.CLIENT_SERVER_RES_ISERVERID_FIELD.cpp_type = 3

_M.CLIENT_SERVER_RES_SZIP_FIELD.name = "szIp"
_M.CLIENT_SERVER_RES_SZIP_FIELD.full_name = ".lobby_gateway.client_server_res.szIp"
_M.CLIENT_SERVER_RES_SZIP_FIELD.number = 3
_M.CLIENT_SERVER_RES_SZIP_FIELD.index = 2
_M.CLIENT_SERVER_RES_SZIP_FIELD.label = 1
_M.CLIENT_SERVER_RES_SZIP_FIELD.has_default_value = true
_M.CLIENT_SERVER_RES_SZIP_FIELD.default_value = ""
_M.CLIENT_SERVER_RES_SZIP_FIELD.type = 9
_M.CLIENT_SERVER_RES_SZIP_FIELD.cpp_type = 9

_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.name = "szDomain"
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.full_name = ".lobby_gateway.client_server_res.szDomain"
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.number = 4
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.index = 3
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.label = 1
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.has_default_value = true
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.default_value = ""
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.type = 9
_M.CLIENT_SERVER_RES_SZDOMAIN_FIELD.cpp_type = 9

_M.CLIENT_SERVER_RES_WPORT_FIELD.name = "wPort"
_M.CLIENT_SERVER_RES_WPORT_FIELD.full_name = ".lobby_gateway.client_server_res.wPort"
_M.CLIENT_SERVER_RES_WPORT_FIELD.number = 5
_M.CLIENT_SERVER_RES_WPORT_FIELD.index = 4
_M.CLIENT_SERVER_RES_WPORT_FIELD.label = 1
_M.CLIENT_SERVER_RES_WPORT_FIELD.has_default_value = true
_M.CLIENT_SERVER_RES_WPORT_FIELD.default_value = 0
_M.CLIENT_SERVER_RES_WPORT_FIELD.type = 13
_M.CLIENT_SERVER_RES_WPORT_FIELD.cpp_type = 3

_M.CLIENT_SERVER_RES.name = "client_server_res"
_M.CLIENT_SERVER_RES.full_name = ".lobby_gateway.client_server_res"
_M.CLIENT_SERVER_RES.nested_types = {}
_M.CLIENT_SERVER_RES.enum_types = {}
_M.CLIENT_SERVER_RES.fields = {_M.CLIENT_SERVER_RES_IERROR_FIELD, _M.CLIENT_SERVER_RES_ISERVERID_FIELD, _M.CLIENT_SERVER_RES_SZIP_FIELD, _M.CLIENT_SERVER_RES_SZDOMAIN_FIELD, _M.CLIENT_SERVER_RES_WPORT_FIELD}
_M.CLIENT_SERVER_RES.is_extendable = false
_M.CLIENT_SERVER_RES.extensions = {}

_M.client_server_req = protobuf.Message(_M.CLIENT_SERVER_REQ)
_M.client_server_res = protobuf.Message(_M.CLIENT_SERVER_RES)

return _M