/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibluejoy_anhuishuangxi_wxapi_WXEntryActivity */

#ifndef _Included_com_ibluejoy_anhuishuangxi_wxapi_WXEntryActivity
#define _Included_com_ibluejoy_anhuishuangxi_wxapi_WXEntryActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibluejoy_anhuishuangxi_wxapi_WXEntryActivity_THUMB_SIZE
#define com_ibluejoy_anhuishuangxi_wxapi_WXEntryActivity_THUMB_SIZE 150L
#ifdef __cplusplus
}
#endif
#endif
